<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kampus_model extends CI_Model
{

    public $table = 'mst_kampus';
    public $id = 'kampus';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        //$this->db->order_by($this->id, $this->order);
        //return $this->db->get_where($this->table,array('uid'=>$this->session->userdata('user_id')))->result();
        $uid = $this->session->userdata('user_id');
        return $this->db->query(
            "SELECT kp.*, p.propinsi, k.kota, iy.instansi
                FROM mst_kampus kp 
                JOIN mst_propinsi p ON kp.id_propinsi = p.id
                JOIN mst_kota k ON kp.id_kota = k.id  
                JOIN mst_instansi_type iy ON  kp.id_instansi_type = iy.id
            WHERE kp.uid = $uid 
            ORDER BY kp.id ASC"
        )->result();
    }

    function get_new_kampus()
    {
        $uid = $this->session->userdata('user_id');
        return $this->db->query(
            "SELECT kp.*, p.propinsi, k.kota, iy.instansi
                FROM mst_kampus kp 
                JOIN mst_propinsi p ON kp.id_propinsi = p.id
                JOIN mst_kota k ON kp.id_kota = k.id  
                JOIN mst_instansi_type iy ON  kp.id_instansi_type = iy.id
            WHERE kp.uid = $uid 
            ORDER BY kp.id DESC
            LIMIT 0,10"
        )->result();
    }

    // get data by id
    function get_by_id($id)
    {
        //$this->db->where($this->id, $id);
        //return $this->db->get($this->table)->row();
        return $this->db->query("SELECT * FROM mst_kampus WHERE id = $id")->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('kampus', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('kampus', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->query(
            "UPDATE 
                mst_kampus 
            SET 
                kampus = '" . $data['kampus'] . "', 
                pimpinan ='" . $data['pimpinan'] . "', 
                email = '" . $data['email'] . "', 
                alamat='" . $data['alamat'] . "', 
                id_propinsi=" . $data['id_propinsi'] . ", 
                id_kota=" . $data['id_kota'] . ",
                longitude='" . $data['longitude'] . "',
                latitude='" . $data['latitude'] . "' 
            WHERE id =" . $id
        );
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Kampus_model.php */
/* Location: ./application/models/Harga_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:04:07 */
/* http://harviacode.com */