<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kota_model extends CI_Model
{

    public $table = 'mst_kota';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    function get_kotakabupaten($id){
        $hasil = $this->db->query("SELECT * FROM mst_kota WHERE id_propinsi='$id'");
        return $hasil->result();
    }

    function get_all_propkota(){
        $hasil = $this->db->query(
            "SELECT 
                p.propinsi, k.kota
            FROM 
             mst_kota k 
            LEFT JOIN mst_propinsi p ON k.id_propinsi=p.id            
        ");
        return $hasil->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table,array('uid'=>$this->session->userdata('user_id')))->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('kota', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('kota', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {   print($data);
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kota_model.php */
/* Location: ./application/models/Harga_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:04:07 */
/* http://harviacode.com */