<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lokasi_model extends CI_Model
{

    public $table = 'mst_lokasi';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        return $this->db->query("SELECT * FROM mst_lokasi")->result();
    }

    // get data by id
    function get_by_id($id)
    {
        //$this->db->where($this->id, $id);
        //return $this->db->get($this->table)->row();
        return $this->db->query("SELECT * FROM mst_lokasi WHERE id = $id")->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('lokasi', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('lokasi', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {   
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {   //echo 'id--------------------:'.$id;print_r($data);die();
        //$this->db->where($this->id, $id);
        //$this->db->update($this->table, $data);
        $this->db->query("
            UPDATE 
                mst_lokasi 
            SET 
                lokasi    = '".$data['lokasi']."', 
                is_active = ".$data['is_active'].",
                tab_name = '".$data['tab_name']."',
                tab_first = ".$data['tab_first']." 
            WHERE 
                id = ".$id);
            
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Lokasi_model.php */
/* Location: ./application/models/Harga_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:04:07 */
/* http://harviacode.com */