<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Type_pegawai_model extends CI_Model {

    public $table = 'mst_pegawai_type';
    public $id = 'id';
    public $uid = 'uid';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        return $this->db->query("SELECT * from ".$this->table)->result();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function update_absensi($id, $id_lokasi, $id_kampus, $uid, $data) {        
        $this->db->where($this->id, $id);
        $this->db->where($this->id_lokasi, $id_lokasi);
        $this->db->where($this->id_kampus, $id_kampus);
        $this->db->where($this->uid, $uid);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transaksi_model.php */
/* Location: ./application/models/Transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:11:34 */
/* http://harviacode.com */